# Generated by Django 3.2.8 on 2023-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustsensorswitch',
            name='lighting',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
