# Generated by Django 3.2.17 on 2023-02-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(max_length=255, verbose_name='메뉴 아이디')),
                ('menu_name', models.CharField(max_length=255, verbose_name='메뉴명')),
                ('menu_parent', models.CharField(max_length=255, verbose_name='상위메뉴 PK')),
                ('menu_link', models.CharField(max_length=255, verbose_name='메뉴 링크')),
                ('menu_order', models.FloatField(null=True, verbose_name='메뉴 정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('user_group', models.ForeignKey(db_column='user_group_id', on_delete=django.db.models.deletion.CASCADE, to='account.usergroup', verbose_name='사용자 그룹')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCheckLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_yn', models.CharField(max_length=2, verbose_name='메뉴사용yn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('menu_id', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, to='menu.menulists', verbose_name='메뉴 아이디')),
                ('user_id', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='사용자 아이디')),
            ],
        ),
    ]
