# Generated by Django 3.2.8 on 2023-02-08 08:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usergroup'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulists',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일자'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MenuCheckLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('menu_name', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, to='menu.menulists', verbose_name='메뉴 아이디')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='사용자 아이디')),
            ],
        ),
    ]
