# Generated by Django 3.2.8 on 2023-02-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230208_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuchecklists',
            old_name='menu_name',
            new_name='menu_id',
        ),
    ]
