# Generated by Django 3.2.8 on 2023-02-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_menu_name_menuchecklists_menu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuchecklists',
            old_name='username',
            new_name='user_id',
        ),
    ]
