# Generated by Django 3.2.8 on 2023-02-09 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usergroup'),
        ('menu', '0004_rename_username_menuchecklists_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulists',
            name='user_group',
            field=models.ForeignKey(db_column='user_group_id', on_delete=django.db.models.deletion.CASCADE, to='account.usergroup', verbose_name='사용자 그룹'),
        ),
    ]
