# Generated by Django 3.2.8 on 2023-02-09 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menulists_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuchecklists',
            name='menu_yn',
            field=models.CharField(default=django.utils.timezone.now, max_length=2, verbose_name='메뉴사용yn'),
            preserve_default=False,
        ),
    ]
