# Generated by Django 3.2.16 on 2023-04-17 01:50

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(null=True, storage=forms.models.OverwriteStorage(), upload_to=forms.models.get_random_filename)),
            ],
        ),
    ]
