# Generated by Django 3.2.8 on 2023-02-08 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='사용자 그룹'),
            preserve_default=False,
        ),
    ]
