# Generated by Django 3.2.8 on 2023-02-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_group_id', models.CharField(max_length=64, verbose_name='사용자 그룹 아이디')),
                ('user_group', models.CharField(max_length=64, verbose_name='사용자 그룹')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일자')),
            ],
            options={
                'verbose_name': '사용자 그룹',
                'verbose_name_plural': '사용자 그룹',
                'db_table': 'user_group',
                'ordering': ['-registered_at'],
            },
        ),
    ]
